### ISSUE TITLE
Mipmap issues for fabric version 1.20.1

### ISSUE THREAD

**Issue by VeggeieDude** [JordanL2/LargeIronSign#1] opened 2024-10-13 09:57 UTC
Heya, awesome mod! However, when I install this mod, mipmapping gets messed up and everything is super jagged.

**Comment by JordanL2** [comment] 2024-10-13 09:59
Can you show a screenshot of what you mean? If you mean general texture mipmapping then it shouldn't have any affect at all...

**Comment by VeggeieDude** [comment] 2024-10-13 10:08
Sure! Here you go

![2024-10-13_06 07 44](https://github.com/user-attachments/assets/fea0da8d-ee08-4184-8f23-802beb30c88c)
This is without the mod
![2024-10-13_06 06 18](https://github.com/user-attachments/assets/b856fb13-6108-44c4-b9d1-712e6f03fa99)
And this is with the mod

It's most notable in the leaves and dirt/grass textures. That is fabric 1.20.1 btw, just used mods, datapacks and resource packs to make it look like beta kinda lol

**Comment by JordanL2** [comment] 2024-10-13 10:29
Just tried it myself in a 1.20.1 instance with/without just this mod. I'm not getting the same result as you, but there is definitely a difference in the rendering of leaves. One side of the leaves looks much darker without the mod.

Without:
![2024-10-13_11 14 23](https://github.com/user-attachments/assets/c90a1062-2947-4e93-a53f-cef371411235)

With:
![2024-10-13_11 16 45](https://github.com/user-attachments/assets/3fe8d636-9f7f-41a5-8bb7-7adfe41c77e0)

Very odd... will look into it. It can only be to do with the custom ModelLoadingPlugin I'm adding, which I thought wouldn't affect anything other than the sign's model.

**Comment by VeggeieDude** [comment] 2024-10-17 08:31
Ok, thanks!

**Comment by JordanL2** [comment] 2024-11-23 16:23
Found very relevant looking logs:
```
 129 [16:11:58] [Worker-Main-5/WARN]: Texture largeironsign:block/large_iron_sign_trim_inside with size 2x1 limits mip level from 4 to 0
 130 [16:11:58] [Worker-Main-5/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1
```
Will try to resize all the textures to 16x16 to see if that fixes it.

**Comment by JordanL2** [comment] 2024-11-23 20:58
@VeggeieDude - I believe I've fixed the issue. All textures smaller than 16x16 have been resized, and I'm not seeing the above message in the logs. The leaves do look a bit better to me now.

This should be fixed in version 1.0.1, downloadable now: https://www.curseforge.com/minecraft/mc-mods/large-iron-sign/files/all?page=1&pageSize=20

**Comment by VeggeieDude** [comment] 2024-11-23 22:41
Awesoome, i will give it a try tonight! Ty 😁

**Comment by JordanL2** [comment] 2024-11-24 17:58
@VeggeieDude did you test and confirm the issue is gone? If so I'll close the issue.

**Comment by VeggeieDude** [comment] 2024-11-24 19:52
Hey sorry not yet, i'll try it tonight sorry! Def will let you know right away if its fixed!

**Comment by VeggeieDude** [comment] 2024-11-24 20:46
Heey, everything looks good! Ty for fixing it 😄

**Comment by JordanL2** [comment] 2024-11-24 20:48
Great! Np, thanks for pointing out the issue.

**Closed as completed by JordanL2** 2024-11-24 20:48 UTC
